# GitLab Pages deployment configuration
# This file enables automatic deployment to GitLab Pages

pages:
  stage: deploy
  script:
    # GitLab Pages expects content in 'public' directory
    - mkdir -p public
    - cp -r index.html data/ themes/ man_pages/ tldr_pages/ public/
    - cp -r .nojekyll LICENSE README.md public/
    - cp -r docs/ public/ || true
  artifacts:
    paths:
      - public
  only:
    # Deploy only from main/master branch
    - main
    - master