# GitLab Pages deployment configuration
# This file enables automatic deployment to GitLab Pages

pages:
  stage: deploy
  script:
    # GitLab Pages expects content in 'public' directory
    - mkdir -p public
    - cp -r index.html data/ public/
    - cp -r .gitignore LICENSE README.md RELEASE_NOTES.md package.json public/ || true
  artifacts:
    paths:
      - public
  only:
    # Deploy only from main/master branch
    - main
    - master